require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/flutter-module-rn/ios/pods'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false


#flutter_application_path = '../../mbflutter_native'
#load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


target 'miniflutter' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
#  install_all_flutter_pods(flutter_application_path)


  target 'miniflutterTests' do
    inherit! :complete
    # Pods for testing
  end

 use_flutter_module_rn!()

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
#    flutter_post_install(installer) if defined?(flutter_post_install)

    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
